name: PR Request

on:
  pull_request:
    types: ["opened", "edited", "auto_merge_enabled"]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: checkov
        run: |
          echo "run checkov"
          echo "terraform init"
          echo "terraform plan -out tf.plan"
          echo "terraform show -json tf.plan  > tf.json"
          echo "checkov -f tf.json"
